spring:
  application:
    name: experiment-app

  datasource:
    url: jdbc:postgresql://localhost:5432/daeseda
    username: jongwon
    password: 1234
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10

#  data:
#    mongodb:
#      uri: mongodb://localhost:27017/your_mongo_db
#    redis:
#      host: localhost
#      port: 6379

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  thymeleaf:
    cache: false

  mail:
    host: smtp.your-email.com
    port: 587
    username: your_email@your-domain.com
    password: your_email_password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  session:
    store-type: redis

server:
  port: 8080

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

---

spring:
  config:
    activate:
      on-profile: dev

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
